// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSDerX2Dbkg8u1lZ08xvizQ7Y4-8bKSis',
    appId: '1:765788376724:web:f550f8522f265b3e472e81',
    messagingSenderId: '765788376724',
    projectId: 'temperature-app-3d881',
    authDomain: 'temperature-app-3d881.firebaseapp.com',
    databaseURL: 'https://temperature-app-3d881-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-app-3d881.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJCyHQmTX6xjs1uktvxWbk-Bc8sfYLw2I',
    appId: '1:765788376724:android:6ccdef2461ab4668472e81',
    messagingSenderId: '765788376724',
    projectId: 'temperature-app-3d881',
    databaseURL: 'https://temperature-app-3d881-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-app-3d881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt1tic3d5LDf6dXHSvyDvHkbz0JtJCTM0',
    appId: '1:765788376724:ios:0d789821d45f5edb472e81',
    messagingSenderId: '765788376724',
    projectId: 'temperature-app-3d881',
    databaseURL: 'https://temperature-app-3d881-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-app-3d881.appspot.com',
    iosBundleId: 'com.example.chartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt1tic3d5LDf6dXHSvyDvHkbz0JtJCTM0',
    appId: '1:765788376724:ios:5e1a3a5a9cb4f07e472e81',
    messagingSenderId: '765788376724',
    projectId: 'temperature-app-3d881',
    databaseURL: 'https://temperature-app-3d881-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-app-3d881.appspot.com',
    iosBundleId: 'com.example.chartApp.RunnerTests',
  );
}
